<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="F_SineFunction" Id="{36c62ab0-3dfd-4d51-af4c-aadf4d024ecd}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_SineFunction : LREAL
VAR_INPUT
	fTime 				: LREAL;
END_VAR
VAR_OUTPUT
	fSineSignal 			: LREAL;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fSineSignal := G_Engineer_HMI.fAmp * SIN(2.0 * PI * G_Engineer_HMI.fFreq * fTime) + G_Engineer_HMI.fSinemidpoint;
G_Motion_Control.fSineReferenceSignal := fSineSignal;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>